steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - eu.gcr.io/niva-cd/haakontest:$SHORT_SHA
    - eu.gcr.io/niva-cd/haakontest:latest
    - .

images: ['eu.gcr.io/niva-cd/haakontest:$SHORT_SHA']