apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: haakontest 
  labels:
    app: haakontest
spec:
  selector:
    matchLabels:
      app: haakontest
  template:
    metadata:
      labels:
        app: haakontest
    spec:
      containers:
      - name: haakontest-container
        image: eu.gcr.io/niva-cd/haakontest:latest
        ports:
          - containerPort: 80 